INSERT INTO AUTHOR(AUTHOR_NAME,AUTHOR_DETAILS) VALUES ('JP LENORD', '24th Lane, College Street Brooklyn');
INSERT INTO AUTHOR(AUTHOR_NAME,AUTHOR_DETAILS) VALUES ('JK ROWLING', '4th Avenue, Linkin Park, London');
INSERT INTO AUTHOR(AUTHOR_NAME,AUTHOR_DETAILS) VALUES ('SIMON TERY', 'Madison Square Garden, USA');

INSERT INTO BOOK(BOOK_NAME,PUBLISHER,AUTHOR_ID) VALUES ('The Files Of North Frontier', 'Brooklyn Press',1);
INSERT INTO BOOK(BOOK_NAME,PUBLISHER,AUTHOR_ID) VALUES ('Harry Potter and The Cursed Child', 'London Press',2);
INSERT INTO BOOK(BOOK_NAME,PUBLISHER,AUTHOR_ID) VALUES ('Jacked Under The Hood', 'US PRESS', 3);

