CREATE SEQUENCE "BOOK_SEQ"
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 4
NOCACHE
NOCYCLE;

CREATE SEQUENCE "AUTHOR_SEQ"
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 4
NOCACHE
NOCYCLE;

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR (
AUTHOR_CODE INT AUTO_INCREMENT  PRIMARY KEY,
AUTHOR_NAME VARCHAR(50) NOT NULL,
AUTHOR_DETAILS VARCHAR(1000) NOT NULL,
SCRIPT_INTRO_LAYOUT TEXT NOT NULL
);

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK (
BOOK_CODE INT AUTO_INCREMENT  PRIMARY KEY,
BOOK_NAME VARCHAR(50) NOT NULL,
PUBLISHER VARCHAR(50) NOT NULL,
AUTHOR_ID INT
);

ALTER TABLE BOOK ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_CODE);



